ministryofjustice/manchester_traffic_offences_pleas

apps/plea/fields.py, apps/plea/forms.py, apps/plea/tests/test_email_template_output.py, apps/plea/tests/test_plea_form.py
Added a new validator to check that the hearing date is not more than 6 months in the future, and updated tests accordingly.
=> Added a new validator to check hearing dates don't exceed 6 months

apps/plea/fields.py, apps/plea/tests/test_audit.py, apps/plea/tests/test_email_template_output.py, apps/plea/tests/test_fields.py, apps/plea/tests/test_plea_form.py, apps/plea/tests/test_validators.py, apps/receipt/tests.py
The app should only be taking entries from URNS starting with 06
as the application is currently only taking pleas in manchester.
[MAPDEV187]
=> Restrict URN entries to ones starting with "06"

apps/plea/email.py, apps/plea/stages.py, apps/plea/tests/test_complete_stage.py, apps/plea/tests/test_email_generation.py, apps/plea/tests/test_plea_form.py, conf/locale/cy/LC_MESSAGES/django.po, manchester_traffic_offences/templates/plea/case.html, manchester_traffic_offences/templates/plea/complete.html, manchester_traffic_offences/templates/plea/plea_email_confirmation.html, manchester_traffic_offences/templates/plea/plea_email_confirmation.txt
Make the court data appear on the case and completion pages.
Tests updated accordingly.
=> Mapdev107 court contact details

manchester_traffic_offences/templates/plea/complete.html
=> Court contact email from the database on the completion screen

apps/plea/tests/test_issues.py, manchester_traffic_offences/settings/base.py, manchester_traffic_offences/settings/testing.py, requirements.txt, requirements/jenkins.txt, requirements/local.txt, requirements/testing.txt
Tidied up the requirements files and added database settings to testing.
=> Fix coverage and unit tests a bit broken

apps/plea/fields.py, apps/plea/forms.py, apps/plea/tests/test_email_template_output.py, apps/plea/tests/test_plea_form.py, manchester_traffic_offences/templates/plea/plea_email_attachment.html, manchester_traffic_offences/templates/plea/review.html, manchester_traffic_offences/templates/plea/your_details.html
New fields added to Your Details screen:
- Is address on Postal Requisition correct
- Updated address (conditional)
- Date of birth
- NI number (optional)
- Driving licence number (optional)
Some help text added or updated as per prototype.
Review screen and emails updated.
All tests updated.
=> Mapdev253 defendant user journey changes

apps/plea/forms.py, manchester_traffic_offences/context_processors.py, manchester_traffic_offences/templates/plea/plea.html, manchester_traffic_offences/templates/plea/review.html
- Hide 'Optional' tag next to 'Not guilty because'
- Remove link to Court Charges doc for now
- Switch phase tag to BETA
=> Additional tweaks

package.json, vagrant/bootstrap.sh
Fixing provisioning issues:
- redis package renamed to correct redis-server
- duplicate npm dependencies removed.
=> Hotfix vagrant provisioning redis

apps/plea/tasks.py, apps/plea/tests/test_audit.py
There was a small bug when retrying tasks with celery. This should now be fixed! 
Tests updated accordingly
[MAPDEV284]
=> Fix celery retry issue

apps/plea/forms.py
Removing hint text and articles before
positions.
[MAPDEV279]
=> Change position options

apps/plea/forms.py, apps/plea/stages.py, apps/plea/tests/test_email_template_output.py, manchester_traffic_offences/templates/plea/review.html
Changed the field to a TypedChoiceField that coerces the value to a
boolean.
Made the same changes to another field for consistency and updated the
template output.
Added email output tests for the expenses section.
[MAPDEV301]
=> Fixed the always yes issue for "other contributors to household bills"

apps/plea/forms.py, manchester_traffic_offences/templates/plea/plea.html
Updated Hint text for Defendant Not Guilty plea.
Updated field notes for all fields on both Defendant and Company rep journeys.
=> Mapdev291 hint text changes

api/settings/base.py, api/v0/serializers.py, apps/plea/migrations/0002_auto_20150518_1537.py, apps/plea/models.py, requirements/base.txt
Some minor amends to make the DX import stuff work.
1) The case_number was 10 digits and it should have been 12, so I've amended and created a migration for it.
2) South was still referenced in the api settings, which I've removed.
NOTE: We need to get the django 1.8 amends live so we can fake the initial before merging and deploying these amends.
=> Mapdev206 data processing

apps/feedback/admin.py, apps/feedback/management/commands/rebuild_aggregates.py, apps/feedback/migrations/0002_auto_20150603_1259.py, apps/feedback/models.py, apps/feedback/tests.py
Updated User Satisfaction aggregation to include raw data for each rating instead of averages, and total number of ratings received.
CSV export updated to recommended format, including question tag and question text (these are mostly used when multiple questions are in place, which isn't the case for MaP, but they are populated for consistency and reference).
Tests updated.
New management command added to rebuild all the weekly aggregates (will be used to retrospectively rebuild on production server from already available satisfaction data)
=> Mapdev292 amend user satisfaction feedback

manchester_traffic_offences/templates/404.html, manchester_traffic_offences/templates/500.html
Changes to meta title and content.
[MAPDEV329]
=> Update error pages

apps/monitoring/check_methods.py, apps/monitoring/tests.py, apps/monitoring/urls.py, apps/monitoring/views.py, manchester_traffic_offences/settings/base.py, manchester_traffic_offences/urls.py, requirements/base.txt
Note: some ops related changes required for this ticket have been
made in an associated branch - MAPDEV314 (in ops)
[MAPDEV320]
=> Added a /healthcheck url which does various diagnostic tests

apps/plea/runner.py, apps/plea/tests/test_audit.py, apps/plea/tests/test_forms.py, apps/plea/tests/test_issues.py, requirements/dev.txt
=> Add some colour to our test output

api/v0/views.py, apps/plea/admin.py, apps/plea/models.py
Returns total number of submissions, guilty and non-guilty pleas per court.
=> Add new API endpoint for court-specific stats

conf/locale/en/LC_MESSAGES/django.po, manchester_traffic_offences/templates/cy/terms.html, manchester_traffic_offences/urls.py, manchester_traffic_offences/views.py
Added TranslatedView class to check for language-specific templates when language code is set.
Created Welsh version of Terms & Conditions template.
Updated translation files to latest.
=> Mapdev372 additional welsh translation

manchester_traffic_offences/settings/base.py, manchester_traffic_offences/settings/dev.py, manchester_traffic_offences/settings/production.py, manchester_traffic_offences/settings/staging.py, manchester_traffic_offences/settings/testing.py, requirements/base.txt, requirements/dev.txt
Reverts ministryofjustice/manchester_traffic_offences_pleas#205
=> Revert "Mapdev364 cookies"

manchester_traffic_offences/settings/base.py, manchester_traffic_offences/settings/dev.py, manchester_traffic_offences/settings/production.py, manchester_traffic_offences/settings/staging.py, manchester_traffic_offences/settings/testing.py, requirements/base.txt, requirements/dev.txt
Reverts ministryofjustice/manchester_traffic_offences_pleas#206
=> Revert "Revert "Mapdev364 cookies""

apps/feedback/stages.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po, manchester_traffic_offences/templates/start.html
Copy updates to start screen, which now mentions NI and driving licence numbers.
Feedback submitted message also updated.
=> Mapdev413 start screen updates

apps/plea/admin.py, apps/plea/stages.py, apps/plea/templates/partials/review_plea.html
If present in the case data and the court has display_case_data set then override the number of charges, display the charge details in the plea pages and titles on the review screen.
Add charge count to case admin list display
=> Get offence data back into the app

apps/plea/fields.py, apps/plea/forms.py, apps/plea/stages.py, apps/plea/templates/partials/review_plea.html, apps/plea/templates/plea.html, apps/plea/tests/test_email_template_output.py, apps/plea/tests/test_plea_form.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
This update adds extra questions to the 'Guilty' option for SJP journeys.
Also included is updates to the review screen, MAPDEV425.
=> MAPDEV424 SJP1 plea screen

api/v0/serializers.py, apps/plea/admin.py, apps/plea/email.py, apps/plea/forms.py, apps/plea/migrations/0008_auto_20151021_1227.py, apps/plea/migrations/0009_auto_20151022_1143.py, apps/plea/models.py, apps/plea/stages.py, apps/plea/tests/test_models.py, apps/plea/tests/test_plea_form.py, apps/plea/tests/test_sjp.py
Capture initiation type and language in case
Capture initiation type and language in stats
Add initiation type and language to case serialiser
Tidy up case / stats admin and add SJP column in to list view
=> Add extra fields for new SJP, welsh data

api/v0/views.py, apps/plea/models.py, apps/plea/tests/test_models.py
Similar functionality to date filtering on main endpoint.
[MAPDEV528]
=> Add date filtering for By Court API endpoint

make_a_plea/settings/testing.py
Pinging @KrisSaxton and @lgarvey 
This change will help us integrate the app in central Jenkins far easier.
=> Dockerization of testings.py settings file.

api/readme.md
=> Add API readme

api/api_test_v0_case.py, api/v0/serializers.py, apps/plea/admin.py, apps/plea/migrations/0026_caseoffencefilter.py, apps/plea/models.py
Add model for offence code whitelisting
Add admin for offence code whitelisting
Update API to prevent offences not in the whitelist being imported
Update API to prevent cases without hearing date being imported
=> Mapdev545 charge filtering

apps/plea/admin.py, apps/plea/templates/admin/datavalidation_change_list.html, apps/plea/templates/admin/statistics.html
Add a view in the datavalidation admin area to give an overview of the total and recent match rates for URN entries.
=> Mapdev551 data validation overview screen

make_a_plea/urls.py
Make the 500 page accessible via /500.html in case of nginx errors which will result in it redirecting to /500.html
=> Add 500.html url

apps/plea/email.py, apps/plea/migrations/0032_auto_20160420_1121.py, apps/plea/models.py, apps/plea/tests/test_audit.py
Adding a completed_on timestamp to the case model to ease generating reports/metrics
Also added in the ou_code and enforcement fields to the court admin, which will be wired up later on.
=> Added completed_on timestamp as well as extra fields to the court model

apps/plea/templates/urn_entry.html, apps/plea/tests/test_stages_data.py, conf/locale/cy/LC_MESSAGES/django.po
Amended the URN error message in response to feedback form the service manager.
=> Amend URN error message + Welsh version, and fix unit test

make_a_plea/urls.py
Add basic healthcheck url for db checking.
=> Add healthchend url

apps/monitoring/templates/monitoring/court_data.html, apps/monitoring/urls.py, apps/monitoring/views.py
Changed the location of each court's data from vertical to horizontal
Tidied the visual styling
Temporarily removed the staff_only requirement and added 24 hour caching
to reduce slow page loads
=> Status page amends

apps/result/templates/emails/user_resulting.html, apps/result/templates/emails/user_resulting.txt, conf/locale/cy/LC_MESSAGES/django.po
Amends have been made to the resulting email - both html and txt
versions in English and Welsh
=> Amend resulting email

Vagrantfile, vagrant/bootstrap.sh, vagrant/pg_hba.conf
Remove dependency on manchester_traffic_offences_ops and makeaplea_dx
Add in required postgres package 
Add pg_hba.conf
=> Fix the vagrant build

apps/plea/forms.py, apps/plea/templates/partials/review_case.html, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
On the review case page, on the case entry form and on the
authentication form.
After discussing with @AlexaVB we agreed that will manually test this
change.
=> RST-229 Change number of charges to offences

apps/plea/fields.py, apps/plea/forms.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
Remove the word 'serious' from 'serious financial problems' and remove the phrase 'For example, you would become homeless'.
=> RST-230 make financial problems not serious

apps/plea/forms.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
Remove the word serious from the 'information for the magistrates' page.
=> RST-230 Remove the word serious

.gitignore, api/api_test_v0_auditevent.py, api/api_test_v0_case.py, api/api_test_v0_result.py, api/api_test_v0_stats.py, api/reusable.py, api/settings/testing.py, api/v0/serializers.py, api/v0/urls.py, api/v0/views.py, apps/plea/admin.py, apps/plea/exceptions.py, apps/plea/migrations/0036_auditevent.py, apps/plea/models.py, apps/plea/tests/test_data_validation.py, apps/plea/tests/test_models.py, apps/plea/validators.py, cucumber/config.yml, cucumber/features/support/boot.rb, make_a_plea/management/commands/generate_fixtures.py, make_a_plea/settings/local.py.example, make_a_plea/settings/testing.py, make_a_plea/tests.py, run_tests.sh
Much discussion happened on https://github.com/ministryofjustice/manchester_traffic_offences_pleas/pull/324. This branch cleans up the history,
=> Added: AuditEvents

apps/plea/encrypt.py, apps/plea/tests/test_encrypt.py, requirements/base.txt
This dependency is being removed as part of upgrading Python
dependencies because it doesn't seem to add anything.
A test for the function has been added to verify the fucntionality
remains the same.
=> Remove dependency on sh package

requirements/testing.txt
=> Added: missing dependency

apps/plea/admin.py, apps/plea/validators.py, make_a_plea/management/commands/generate_fixtures.py
Removes complexity around some aspects of the admin screens to increase performance. Also includes a tool to generate random data in quantity for performance testing. Some minor fixes to style and performance generally.
=> Fixed: RST340 - Improve django admin performance

docker/run_celery.sh
This reorders the parameters to match the docs and adds INFO logging for
a bit more detail in the logs.
=> Add INFO logging to celery

apps/plea/tests/test_stats.py, apps/plea/urls.py, apps/plea/views.py, make_a_plea/exceptions.py, make_a_plea/helpers.py, make_a_plea/middleware.py, make_a_plea/settings/base.py
Court staff would like to view a summary of cases by language.
=> Added: RST-328, staff-only case summary by language

apps/plea/tests/test_stats.py, apps/plea/urls.py, apps/plea/views.py, make_a_plea/tests.py
This feature was accidentally removed during a rebase. This PR adds it back in.
=> Added: stats by language, again

conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
Update the language files. This change just updates the line numbers and
some file names (wierdly they had been listed as .html.py files)
=> Run makemessages.sh

apps/plea/templates/plea.html, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po, make_a_plea/templates/start.html
The Welsh translations here have now been verified.
=> RST 385 replace discount with reduction

apps/forms/fields.py, apps/forms/forms.py, apps/forms/stages.py, apps/forms/templates/widgets/multi_field.html, apps/forms/templates/widgets/partials/DSRadioSelect.html, apps/forms/templates/widgets/partials/label_text.html, apps/forms/templates/widgets/plea_radio_field.html, apps/forms/templates/widgets/std_field.html, apps/forms/templatetags/filters.py, apps/plea/stages.py, apps/plea/templates/plea.html, apps/plea/templates/your_status.html, apps/plea/views.py, requirements/base.txt
Modified: Your Details page now works going backwards
Modified: Improved formatting in certain areas
Updated: Django to 1.11.3
=> Fixed: radio buttons

requirements/base.txt
Switch to the officially released package as well.
=> Upgrade govuk_template

requirements/base.txt
Noticed a UI bug when deployed to dev.
Reverts ministryofjustice/manchester_traffic_offences_pleas#364
=> Revert "Upgrade govuk_template"

make_a_plea/management/commands/fixture_categories.py, make_a_plea/management/commands/fixture_methods.py, make_a_plea/management/commands/fixtures.py, make_a_plea/tests.py
Adding richer fixtures to allow for better testing.
=> Fixed: Improved richness of fixtures

.travis.yml, requirements/testing.txt
- print out report in travis job
- submit to code climate
- only submit coverage for pushes to master
=> Add code coverage report

features/case_details.feature, features/notice_type.feature, features/step_definitions/case_details_steps.rb, features/step_definitions/common_steps.rb, features/step_definitions/company_details_steps.rb, features/step_definitions/notice_type_steps.rb, features/step_definitions/your_details_steps.rb, features/step_definitions/your_plea_guilty_steps.rb, features/step_definitions/your_plea_not_guilty_steps.rb, features/step_definitions/your_plea_steps.rb, features/support/env.rb, features/support/generic_helpers.rb, features/support/page_objects/case_details_page.rb, features/support/page_objects/common_page.rb, features/support/page_objects/notice_type_page.rb, features/support/page_objects/your_details_page.rb, features/support/page_objects/your_plea_guilty_page.rb, features/support/page_objects/your_plea_not_guilty_page.rb, features/support/page_objects/your_plea_page.rb, features/your_details.feature, features/your_plea.feature, features/your_plea_guilty.feature, features/your_plea_not_guilty.feature, features/your_plea_validation.feature
New feature files:
case_details.feature
your_details.feature
your_plea.feature
your_plea_guilty.feature
your_plea_not_guilty.feature
your_plea_validation.feature
=> RST-518 new cucumber end to end feature files

features/company_details.feature, features/step_definitions/company_details_steps.rb, features/support/generic_helpers.rb, features/support/page_objects/company_details_page.rb
UI e2e tests for MaP company details page
/plea/company_details/
=> RST-520 cucumber tests for company details

features/company_details.feature, features/company_plea.feature, features/step_definitions/common_steps.rb, features/step_definitions/company_plea_steps.rb, features/step_definitions/your_plea_guilty_steps.rb, features/step_definitions/your_plea_not_guilty_steps.rb, features/support/generic_helpers.rb, features/support/page_objects/common_page.rb, features/support/page_objects/company_plea_page.rb, features/support/page_objects/your_plea_guilty_page.rb, features/support/page_objects/your_plea_not_guilty_page.rb
Jira https://tools.hmcts.net/jira/browse/RST-536
=> RST-536 company plea feature

api/settings/production.py, api/settings/staging.py, api/settings/testing.py, make_a_plea/settings/base.py, make_a_plea/settings/testing.py
**Change personal emails for Admins to HMCTS Reform email groups**
=> Change personal emails for Admins to HMCTS Reform email groups

apps/plea/email.py, apps/plea/forms.py, apps/plea/templates/company_details.html, apps/plea/templates/emails/attachments/plea_email.html, apps/plea/templates/emails/attachments/plp_email.html, apps/plea/templates/partials/review_details.html, apps/plea/templates/review.html, apps/plea/templates/your_details.html, apps/plea/tests/test_email_generation.py, apps/plea/tests/test_email_template_output.py, apps/plea/tests/test_issues.py, apps/plea/tests/test_plea_form.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po, make_a_plea/views.py
Moves the email used for sending the confirmation to the your_details
and company_details stages.
This is now ready for review.
=> RST-386 Move email to your details

features/case_details.feature, features/company_details.feature, features/company_plea.feature, features/enter_urn.feature, features/step_definitions/case_details_steps.rb, features/step_definitions/common_steps.rb, features/step_definitions/company_details_steps.rb, features/step_definitions/enter_urn_steps.rb, features/step_definitions/your_details_steps.rb, features/step_definitions/your_plea_guilty_steps.rb, features/step_definitions/your_plea_not_guilty_steps.rb, features/step_definitions/your_plea_steps.rb, features/support/generic_helpers.rb, features/support/page_objects/company_details_page.rb, features/support/page_objects/your_details_page.rb, features/support/page_objects/your_plea_page.rb, features/your_details.feature, features/your_plea.feature, features/your_plea_guilty.feature, features/your_plea_not_guilty.feature, features/your_plea_validation.feature
Updated cucumber tests for email address and some refactoring
=> RST-386 cucumber tests for email address 

features/review.feature, features/step_definitions/review_steps.rb, features/support/generic_helpers.rb, features/support/page_objects/review_page.rb, features/your_details.feature
https://tools.hmcts.net/jira/browse/RST-595
=> RST-595 review page cucumber

apps/forms/stages.py, apps/plea/views.py, make_a_plea/settings/base.py
This needs to be tested on staging as I'm unable to see if it works locally.
=> Added logging to areas to suspect redirect areas

make_a_plea/settings/docker.py
**Allow multiple values for ALLOWED_HOSTS**
=> Allow multiple values for ALLOWED_HOSTS

apps/plea/forms.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po
https://tools.hmcts.net/jira/browse/RST-1693
=> Rst 1693 add ni and dl links

requirements/base.txt
https://tools.hmcts.net/jira/browse/RST-1942
=> RST-1942: Update libraries with lastest versions

requirements/base.txt
https://tools.hmcts.net/jira/browse/RST-1967
=> 1967: Update Django library

requirements/base.txt
Github alert showed upgrade of django version was needed.
=> Update to later version

apps/plea/forms.py, conf/locale/cy/LC_MESSAGES/django.po, conf/locale/en/LC_MESSAGES/django.po, make_a_plea/templates/base_form.html
https://tools.hmcts.net/jira/browse/RST-2094 & https://tools.hmcts.net/jira/browse/RST-2095.
=> Remove "see highlighted errors" and add help text for date format.

.circleci/config.yml, deploy/development/map-app/deployment-web-app.yaml, docker/Dockerfile, docker/run_celery.sh, make_a_plea/settings/dev.py
https://tools.hmcts.net/jira/browse/RST-6150
=> RST-6150 add celery container and sqs queue

apps/plea/email.py, apps/plea/encrypt.py, make_a_plea/settings/docker.py
Change default setting of STORE_USER_DATA back to True
Don't even attempt to send prosecutor email as it isn't required (courts forward them)
Log the plea attachment encryption
=> Plea attachment saving
