- apps/plea/stages.py
- apps/plea/tests/test_plea_form.py
When the plea screen was submitted without a plea chosen it was
redirecting to the case screen without error. A fix has been
applied and some tests added.
[MAPDEV139]
> Fix for redirection bug in plea entry screen

- apps/plea/fields.py
The django multiwidget we were using was returning data [None, None, None]
when all fields were empty, this was triggering the wrong validation
message. Now if all field values are empty value_from_datadict returns
an empty string.
[MAPDEV132]
> Hearing date field showing invalid format error when empty

- apps/plea/forms.py
- apps/plea/stages.py
- manchester_traffic_offences/templates/widgets/money_field.html
- manchester_traffic_offences/templates/widgets/radio_field.html
- manchester_traffic_offences/templates/widgets/std_field.html
- manchester_traffic_offences/templates/widgets/wide_field.html
On the 'Your money' screen, all fields are required, but this requirement
needs deactivating for validation to catch only the relevant fields. Now a
'hide_optional' context var can be set to force hide the 'Optional' tag.
> Remove 'optional' tag using context var

- requirements/base.txt
This allows using the js_gt_ie template block to filter the minimum
IE version that gets JS functionality. Also resolves the issue of
empty conditional tag being rendered in IE6~8.
> MoJ Template version update

- apps/plea/admin.py
- apps/plea/email.py
- apps/plea/models.py
- apps/plea/tasks.py
- apps/plea/tests/test_audit.py
- apps/plea/tests/test_fields.py
- apps/plea/tests/test_plea_form.py
- apps/receipt/process.py
- apps/receipt/tests.py
The inline status fields on the case table wasn't expressive enough to
capture all of the actions of sending emails via celery tasks and
processing receipts. We've moved to a more immediate set of boolean
flags on the case and emailcount objects and also a list of actions
on the case object.
[MAPDEV167]
> Migrate inline statuses to an action list

- manchester_traffic_offences/assets-src/javascripts/modules/moj.CalculateTotals.js
- manchester_traffic_offences/assets-src/tests/moj.CalculateTotals.spec.js
- manchester_traffic_offences/assets/javascripts/application.js
Non-numeric values would return NaN -- this is now fixed. Test updated.
[MAPDEV158]
> Handle non-numeric values

- manchester_traffic_offences/assets-src/javascripts/modules/moj.TemplatedElement.js
- manchester_traffic_offences/assets-src/tests/moj.TemplatedElement.spec.js
- manchester_traffic_offences/assets/javascripts/application.js
When mutliple elements are set as delegates, the default text was
a concatenation of the text from all elements. From now on only the first
one is used.
[hotfix]
> Templated Element Module - Fix mutliple delegates default text

- manchester_traffic_offences/templates/plea/complete.html
Message displayed was only tailored for fully 'guilty' or 'not guilty'
pleas, ignoring mixed cases. A single message has been added (mixed
pleas are always plural!)
> Fix missing mixed pleas message on Success screen

- apps/plea/forms.py
- conf/locale/cy/LC_MESSAGES/django.po
The 'For example' part was missing; now added.
> Add second part of URN hint text

- apps/govuk_utils/forms.py
- apps/plea/tests/test_issues.py
- apps/plea/views.py
- manchester_traffic_offences/templates/plea/urn_used.html
Users were somehow (still not identified how) getting back into the
forms with a used URN still in session. The path for this wasn't
quite dealing with the situation, this removes the code causing the
error from the execution path, allowing the "URN already used" page
to be displayed.
[MAPDEV269]
> Hotfix for stage not set issue

- apps/plea/tasks.py
- apps/plea/tests/test_email_generation.py
- manchester_traffic_offences/templates/plea/complete.html
- manchester_traffic_offences/templates/plea/complete/email_html/whats_next_company.html
- manchester_traffic_offences/templates/plea/complete/email_html/whats_next_defendant.html
- manchester_traffic_offences/templates/plea/complete/email_txt/whats_next_company.txt
- manchester_traffic_offences/templates/plea/complete/email_txt/whats_next_defendant.txt
- manchester_traffic_offences/templates/plea/complete/screen/whats_next_company.html
- manchester_traffic_offences/templates/plea/complete/screen/whats_next_defendant.html
- manchester_traffic_offences/templates/plea/plea_email_confirmation.html
- manchester_traffic_offences/templates/plea/plea_email_confirmation.txt
'Complete' screen and confirmation email updates
Includes revised wording in the heading and "what's next" list, across screen, HTML email and text-only email versions. "What's next" lists have been abstracted for code clarity.
Email tests also updated: these were only testing the text-only version; they now check the HTML version.
> Complete screen updates

- manchester_traffic_offences/templates/start.html
Updated copy throughout all sections.
Replaced `trans` blocks with `blocktrans` for better code readability.
Removed unused `.before-start` class.
Add class `.text` to main column content to wrap text better on larger screens.
> Update start screen copy

- apps/plea/fields.py
- apps/plea/forms.py
- apps/plea/tests/test_email_generation.py
- apps/plea/tests/test_email_template_output.py
- apps/plea/tests/test_plea_form.py
- manchester_traffic_offences/templates/plea/company_details.html
- manchester_traffic_offences/templates/plea/review/details.html
Updated Company rep journey address input to match pattern used for Defendant journey: first a question whether address on requisition pack is correct, with an extra field to add updated address if not.
Error messages for Company rep journey based on Defendant journey messages.
New tests added for Company rep journey, also added to Defendant journey as these weren't present.
> Mapdev302 company address pattern

- apps/govuk_utils/stages.py
- apps/plea/stages.py
- apps/plea/tests/test_plea_form.py
If the hardship question wasn't answered (which is the case
in the first step of the NoJS journey), the stage was redirecting
to the review screen, which in the case of the NoJS journey
is incorrect.
We are now resetting the `Complete` flag for each step when a
NoJS POST is done. This will prevent users from being able to
navigate back to the `Review` screen by updating the URL directly
after only updating the first step of a NoJS question.
Also fixed a bad reference to multiple forms construct in new 'updated address' tests.
> Hotfix non js redirect error

- apps/plea/admin.py
- apps/plea/email.py
- apps/plea/migrations/0003_courtemailcount_court.py
- apps/plea/models.py
- apps/plea/tests/test_models.py
- apps/receipt/tests.py
With the application now able to take pleas in different areas it
has been noted that the anon stats should be able to break down
by the area in which the plea was made.
This commit adds a field for court into the anon stats model and
updates the application code and tests to pass in court where
required.
[MAPDEV281]
> Added court field, migrations and updated tests.

- apps/plea/migrations/0002_auto_20150602_1636.py
- apps/plea/migrations/0003_auto_20150602_1658.py
- apps/plea/migrations/0004_merge.py
- apps/plea/models.py
A few minor field amends have been made to accommodate the DX integration: 
1) the case_number and offence_short_title fields have had been altered to match the char length values in the dx/libra case xsd
2) the ou code has been moved from the offence model to the case model, where it belongs.
I had a migration clash, which seemed to resolve when I ran ./manage makemigrations --merge. If it persists when deployed to dev/staging, I'll manually merge the migrations into a single file.
> Amends made to case and offence model fields for DX

- apps/plea/fields.py
- apps/plea/forms.py
Add validator to prevent entering dates in the future.
Also tidied up existing custom validators to move the error messages to the form schema, alongside where all other error messages are set. Default error messages in the validators themselves now make more sense in context, and are more generic.
Fix one remaining occurrence of 'postal requisition'.
> Mapdev311 dob validation

- apps/plea/email.py
- apps/plea/fields.py
- apps/plea/migrations/0004_court_validate_urn.py
- apps/plea/models.py
- apps/plea/tests/test_validators.py
Individual courts can now be switched on to ensure the case record is
present in the database before proceeding.
Added option for court in model and updated validator.
[MAPDEV207]
> Courts can now be switched to use URN validation

- apps/plea/tasks.py
- manchester_traffic_offences/celery.py
- manchester_traffic_offences/settings/base.py
- requirements/base.txt
The retry on failed tasks was happening immediately instead of
delaying 90 seconds as required. This was due to the tasks results
being discarded. A django-orm backend has been added as a first
pass with the option of moving it to redis or a cache later.
[MAPDEV280]
> MAPDEV280 Added django-celery task backend to enable failed tasks to retry

- apps/plea/stages.py
- manchester_traffic_offences/templates/plea/review.html
When calculating expense totals, each expense
value was incorrectly cast as integer instead of
being treated as float.
[hotfix]
> Fix rounded total expenses

- apps/plea/stages.py
- manchester_traffic_offences/templates/plea/complete.html
These add new GA events at the end of a journey (on the Complete screen).
For all journeys:
- Complete submission: Plea made by (Defendant/Company representative)
For 'Defendant' journeys:
- Complete submission: NI number (yes/no)
- Complete submission: Driving licence number (yes/no)
[MAPDEV345]
> Add end-of-journey analytics

- apps/plea/tasks.py
- apps/plea/tests/test_email_template_output.py
When a journey was entered using the Welsh language version of
the site, the resulting Court and Police emails were being sent in
Welsh.
Added a decorator to both Court and Police email senders to force
English language.
[MAPDEV378]
> Fix language of Court and Police emails

- apps/plea/email.py
- apps/plea/templates/emails/attachments/plea_email.html
- apps/plea/tests/test_email_template_output.py
For journeys completed using the Welsh version of the site,
this adds an extra section called 'Language' to the plea email.
[MAPDEV371]
> Add Welsh flag to emails for Welsh journeys

- manchester_traffic_offences/settings/base.py
- manchester_traffic_offences/settings/dev.py
- manchester_traffic_offences/settings/production.py
- manchester_traffic_offences/settings/staging.py
- manchester_traffic_offences/settings/testing.py
- requirements/base.txt
- requirements/dev.txt
Combines tickets MAPDEV364, MAPDEV367 and MAPDEV363
Set up encrypted cookies https://github.com/brightinteractive/django-encrypted-cookie-session
And added the CSRF_COOKIE_HTTPONLY and CSRF_COOKIE_SECURE flags to settings so now that both the session cookie and the csrf cookie are secure and httponly and the session cookie should now be both signed and encrypted.
> Mapdev364 cookies

- apps/feedback/tests.py
- apps/feedback/views.py
- apps/plea/middleware.py
- apps/plea/templates/plea.html
- apps/plea/tests/test_timeout.py
- apps/plea/views.py
This prevents the whole session having to be nuked on
completion, meaning things like language settings get
preserved: the feedback now appears in Welsh after
completing the journey in Welsh.
[MAPDEV406]
> Update Plea journey to use its own session key

- apps/govuk_utils/stages.py
- apps/plea/views.py
The user was previously being redirected to the Case Details screen after completing a plea,
which made little sense.
Also added more specific debug message to the 404 that is thrown when
the stage is not set.
> Redirect to Start screen after providing feedback at end of plea

- apps/feedback/views.py
- apps/monitoring/views.py
- apps/plea/views.py
- make_a_plea/settings/base.py
- make_a_plea/urls.py
- make_a_plea/views.py
This update applies a cache-control max-age of 0 to all requests, and
should prevent a Safari bug where the browser is aggressively caching
previously requested pages.
This also removes the need for a lot of the 'never_cache' method
decorators on dispatch definitions -- the HomeView has also been removed
and replaced with a standard TemplateView.
[MAPDEV448]
> Set cache middleware default to 0 seconds

- apps/plea/email.py
- apps/plea/models.py
- apps/plea/stages.py
- apps/plea/templates/complete.html
- apps/plea/templates/emails/user_plea_confirmation.html
- apps/plea/templates/emails/user_plea_confirmation.txt
- apps/plea/tests/test_audit.py
- apps/plea/tests/test_email_generation.py
- apps/plea/tests/test_email_template_output.py
- apps/plea/tests/test_models.py
- apps/plea/tests/test_plea_form.py
- conf/locale/cy/LC_MESSAGES/django.po
- conf/locale/en/LC_MESSAGES/django.po
- make_a_plea/templates/base_user_email.html
- make_a_plea/views.py
Copy updates
Contact deadline gets set when saving the Case stage: it is either the
hearing date for non-SJP cases, or the posting date +28 days for SJP
cases.
Note: this contact deadline date is used for the Court Email Count stats
when the case is SJP.
[MAPDEV430]
Update User confirmation email
Copy updates for both Defendant and Company journeys.
Remove capitalised 'Post'
Some small style updates:
- Extra CSS content block for more granular styling in various templates
- H1 heading now 36px
- H2 headings font-size now 24px
- Main padding around email content is now 10px for better use of screen real estate on smaller devices
- Smaller headings ("By post:" and "By email:") are now H3.
[MAPDEV431]
> MAPDEV430 Update Confirmation screen

- apps/feedback/templates/comments.html
- apps/feedback/templates/emails/feedback_summary.html
- apps/feedback/tests.py
Email field now always shows, previously was hidden when user had
selected they had used the call centre.
Removed test for show/hide email field, replaced with form loading test.
Updated feedback email to always include Comments and Email, but
defaulted to "-".
[MAPDEV447]
> MAPDEV447 feedback email field

- apps/feedback/tests.py
- apps/feedback/views.py
- apps/plea/stages.py
- apps/plea/views.py
- make_a_plea/templates/base.html
Completing the feedback form just after a successful submission was redirecting the user to the Notice Type screen, when they should be redirected to the Start screen instead.
When session is missing, the user is now also redirected to the start page rather than the first stage, but is also shown a message about the session having timed out.
[MAPDEV463]
> Mapdev463 feedback redirect

- apps/plea/stages.py
- apps/plea/tests/test_nojs.py
Dependencies on "company_details" and "plea" stages were missing for the company finances stage,
meaning it was accessible without completing these.
[hotfix]
> Fix missing dependencies for Company Finances

- apps/plea/admin.py
- apps/plea/migrations/0012_court_notice_types.py
- apps/plea/migrations/0013_remove_court_sjp_area.py
- apps/plea/models.py
- apps/plea/stages.py
- apps/plea/tests/test_plea_form.py
The SJP area setting has been replaced by a more modular Notice Types setting, which can be set to 'SJP', 'Non-SJP' or 'Both'.
When the user submits URN, if the Court is set to accept either only SJP notices or only non-SJP notices, the Notice Type is automatically set and the Notice Type stage is skipped. If a URN for a Court accepting both is submitted, then the Notice Type screen is still shown.
If the Notice Type has been set automatically as above, trying to access the Notice Type screen redirects the User to the Case screen.
> Mapdev503 sjp user journey for lh

- apps/plea/email.py
- apps/plea/tasks.py
Setting the case 'sent' flag in the main email script was being
superseded by the Court email task. This task now checks for the court
test mode before attempting to set the flag: if the court is in test
mode, the case isn't marked as sent, allowing the URN to be reuse for
multiple tests.
[MAPDEV506]
> Move case sent update to court email send

- apps/plea/stages.py
- apps/plea/templates/case.html
- apps/plea/tests/test_plea_form.py
If DX data is available and offences are correctly listed, the number of
charges is set automatically and the field is hidden.
[MAPDEV509]
> Use DX data to set number of charges

- run_tests.sh
This is script is called by central jenkins during the TEST-docker-manchester_traffic_offences_pleas jobs.
> Adding a script for running tests.

- .gitignore
- api/settings/base.py
- api/settings/testing.py
- run_api_tests.sh
- run_tests.sh
- Remove unnecessary project_app dependency on moj_template
- Add environment variables DB settings to API testing settings
- Add pip install to API test script
- Uncomment API testing from main test script
[hotfix]
> Fix test scripts

- api/api_test_v0_stats.py
- api/v0/views.py
When an incorrect or invalid date is passed as a parameter to either the `/v0/stats/` or the `/v0/stats/by_court/` endpoints, the Public API now returns an error instead of a server error.
Tests added for all Public API endpoints.
> Mapdev539 handle api error gracefully

- apps/feedback/email.py
- apps/feedback/stages.py
- apps/feedback/templates/complete_feedback.html
- apps/feedback/tests.py
- apps/feedback/views.py
- make_a_plea/settings/production.py
- make_a_plea/tests.py
- make_a_plea/urls.py
- make_a_plea/views.py
As it stood, a successfull feedback submission would produce a success
flash message on the redirect screen. This was a problem when the
redirect screen was the start screen, as this is now hosted on gov.uk.
To avoid this issue, submitting feedback now results in a standalone
confiramtion screen. This screen shows a Finish button which takes the
user back to where they were when they started giving feedback.
[MAPDEV497]
> Add Feedback submission confirmation screen

- apps/forms/forms.py
- apps/forms/tests.py
Fields that are only required when another field is set to a certain
value were still erroring on other validation issues. This update
removes the field value form the form data if it is not required
anymore, to prevent such other validation errors.
As a bonus side-effect, this update also helps pruning data that isn't necessary form the session.
[MAPDEV543]
> Fix validation error bug on non-required field

- Dockerfile
- run.sh
Added a run.sh file that handles a DOCKER_STATE var, so that the parameterised build job in Jenkins can run various django commands.  Currently we're only handling a database migration.
> Added a run.sh for docker that handles a DOCKER_STATE env var

- make_a_plea/settings/base.py
- requirements/base.txt
Entering 3 wrong passwords will lead to a 1 hour lock out.
This PR contains DB migrations
> Added django-axes for admin password lockout

- make_a_plea/settings/docker.py
- make_a_plea/views.py
Minor amend to make REDIRECT_START_PAGE work with template-deploy and the single settings file (docker.py).
I think going forward it'd be easier if we do split up the settings files so we have the usual settings/staging.py, settings.prod.py etc. But for now this should work.
> Amend home page redirect so that it works with TD setup

- apps/plea/stages.py
- apps/plea/tests/test_stages_data.py
- make_a_plea/management/commands/check_urns_in_db.py
Drops out of the data route if multiple cases are found for a given URN, but only if records aren't identical. This is to account for the fact that the data may contain cases with different defendants under the same URN as well as duplicate case data.
> Mapdev558 duplicate cases in data route

- apps/plea/stages.py
- apps/plea/tests/test_stages_data.py
Quick fix to prevent offence data from showing if the user does not auth or if DX is not enabled.
> Fix to prevent offence data from showing if the user does not auth

- apps/plea/admin.py
- apps/plea/migrations/0031_case_created.py
- apps/plea/models.py
- apps/result/admin.py
- apps/result/migrations/0003_result_created.py
- apps/result/models.py
Amends and migrations added to add the time stamp field to the Result and Case models, and to add a read-only copy of the field to the admin.
This will aid in data investigation when we need to determine when a record was created to try to locate it in the source DX files.
> Added timestamp field which is visible in the admin

- apps/plea/email.py
- apps/plea/forms.py
- apps/plea/models.py
- apps/plea/stages.py
- apps/plea/templates/authenticate.html
- apps/plea/templates/urn_entry.html
- apps/plea/templates/your_details.html
- apps/plea/tests/test_authentication.py
- apps/plea/tests/test_data_validation.py
- apps/plea/tests/test_issues.py
- apps/plea/tests/test_stages_data.py
- apps/plea/validators.py
The authenticated journey has now been modified so when court has strict validation enabled we require a valid URN (e.g. exists in the database and has not been pled against) and  the correct number of charges, and a valid date of birth. If the DOB Is not present in the incoming libra data, we use the defendants postcode and that isn't available, the user will receive an error message telling them to complete the offline requisition forms instead.
TODO:
Change some validation text 
Fix remaining unit tests
> Modified authentication

- apps/plea/admin.py
- apps/plea/email.py
- apps/plea/migrations/0033_auto_20160505_1421.py
- apps/plea/migrations/0034_auto_20160519_1047.py
- apps/plea/migrations/0035_auto_20160519_1055.py
- apps/plea/models.py
- apps/plea/stages.py
- apps/plea/tasks.py
- apps/plea/templates/partials/review_details.html
- apps/plea/tests/test_email_generation.py
- apps/plea/tests/test_models.py
- apps/plea/views.py
- apps/result/management/commands/process_results.py
- make_a_plea/settings/docker.py
A temporary OU code based routing "hack" to allow the Bromley region to exist alongside Lavender Hill. 
At currently the make-a-plea app determines which court should receive defendant submission emails based on the first two digits of the URN code, but as Bromley and Lavender Hill share the same region, this won't work.
So we're now using the OU code which is supplied for each case by Libra, which correctly identifies the court that a case belongs to.
> Oucode court selection

- make_a_plea/management/commands/delete_old_data.py
- make_a_plea/settings/base.py
- make_a_plea/tests.py
Add a management command ./manage.py delete_old_data that removes any data older than {settings.DATA_RETENTION_PERIOD} days old.
Associated pull requests have also been made to the ops and soap gateway repos.
> Add a management command to cull old case and resulting data

- apps/result/management/commands/generate_result_csv.py
HMCTS need to confirm that the resulting data provided by CGI is valid. Particularly they need to confirm that account numbers and division codes are correct for each result.
To aid them I've added a django management command that will generate a list of all the results for a given day with as much ancillary result and case information as possible.
> Add a command to generate a csv of results and relevant case data

- apps/result/management/commands/generate_result_csv.py
The CSV command has been amended so that it can list results that have been marked as resulted, using a --show-all option, e.g. 
./manage.py generate_result_csv --show-all
Also the output of the fines, endorsements and division code fields has been cleaned up.
> Add option to show all results, including those that have been resulted

- apps/plea/models.py
- apps/plea/tests/test_models.py
The court responsible for processing a submission is primarily
determined by the first two digits (the region code) of the URN. Some
courts share a region code, so we determine the correct court for a
submission based on the OU code supplied by Libra.
The old logic would attempt to match on OU code first, however we now
haev a situation where we have two courts with the same OU codes but
different region codes. To enable this to work the court look up
functionality has been modified to look up a court on both OU code and
region code and if this fails, it will fall back to a region code look
up.
> Ensure OU code based court lookup also use region

- vagrant/bootstrap.sh
This change adds some missing dependencies to the Vagrant bootstrapping script that tripped me up when starting out with this project.
The `gettext` dependency is required in order to compile the language files.
The test dependencies are added so that tests can easily be run on the Vagrant box.
The language messages are compiled so that the correct language text is inserted.
> Fix up Vagrant bootstrap

- apps/plea/templates/emails/user_plea_confirmation.txt
- apps/plea/templates/emails/user_plea_confirmation_sjp.txt
- apps/plea/tests/test_email_template_output.py
- apps/result/templates/emails/user_resulting.txt
- apps/result/tests.py
- conf/locale/cy/LC_MESSAGES/django.po
- conf/locale/en/LC_MESSAGES/django.po
- make_a_plea/templates/base_user_email.html
As the MaP Service Manager I want users to contact the relevant court and not the MaP email address as the tickets that are received in ZenDesk cannot be actioned by anyone working on Make a Plea.
I have added tests to verify that the text has been removed from the relevant emails. This tests are not so useful long term and could be cleaned up.
> RST-144 Remove 'forward email' section from emails

- apps/plea/templates/company_details.html
- apps/plea/templates/court_finder.html
- apps/plea/templates/review.html
- apps/plea/templates/urn_entry.html
- apps/plea/templates/urn_used.html
- apps/plea/templates/your_details.html
- apps/result/management/commands/process_results.py
- apps/result/models.py
- apps/result/tests.py
- conf/locale/cy/LC_MESSAGES/django.po
- conf/locale/en/LC_MESSAGES/django.po
It looks like lots of small manual changes have been made without running `makemessages.sh`. As a result when `makemessages.sh` is run there are a few bits to tidy up and a few missing translations added.
It looks like this file has been manually edited for a while which has resulted in it drifting away from the layout that gettext uses. This change is the result of running the following command and tidying up the output.
```python ./manage.py makemessages --locale=cy --ignore=node_modules/* --no-wrap```
The benefit of doing this is that we can easily verify the file against the english file with something like vimdiff.
There are some untranslated items (marked with TODO) that need to be sent to the Welsh translation unit.
There were translations for most of the result email (except for …
> Result email translation

- .travis.yml
- Dockerfile
- apt/development.sh
- apt/production.sh
- apt/testing.sh
- make_a_plea/settings/testing.py
- vagrant/bootstrap.sh
This change introduces a `.travis.yml` file so that the unit tests can
be run in travis against each branch. It also moves apt dependencies out
into separate scripts so that they can be more consistently shared
between `Dockerfile`, Vagrant and Travis.
I have not included npm asset building because apparently the assets are
committed to the repo and re-building is done as an offline task.
> Run tests in Travis

- apps/result/models.py
- apps/result/tests.py
Some investigation has shown that the Welsh result wording
(`ResultOffenceData.result_wording_welsh`) often has just whitespace in
it. This change first trims the value when testing whether it's empty.
Given that there is a risk that the Welsh result wording may have
text in it that does not correctly represent the result wording I have
changed the code that scans the wording for the fine value back to using
the English wording only.
> Improve Welsh ofence display in result email

- apps/plea/templates/emails/user_plea_confirmation.html
- apps/plea/templates/emails/user_plea_confirmation.txt
- apps/plea/templates/emails/user_plea_confirmation_sjp.html
- apps/plea/templates/emails/user_plea_confirmation_sjp.txt
- apps/result/templates/emails/user_resulting.html
- apps/result/templates/emails/user_resulting.txt
- conf/locale/cy/LC_MESSAGES/django.po
- conf/locale/en/LC_MESSAGES/django.po
Add 'do not reply' text to the automated emails.
The user is still provided a way to reply but not via the from address
of the email.
> RST-143 Add 'do not reply' text to emails

- api/settings/base.py
- api/settings/docker.py
- make_a_plea/settings/base.py
- make_a_plea/settings/docker.py
RST-210 highlighted that non-production URLs were being sent out in
production emails. This change fixes that and defaults them to
production URls. There is a corresponding change in the deployment
scripts to set an appropriate base URL in each environment.
> Use production URLs in emails

- .gitignore
- make_a_plea/management/commands/zendesk.py
- requirements/dev.txt
Exports data from zendesk to csv. You can store your zendesk config and queries in a config file and run the command to create the csv file with current data. It is not restricted to makeaplea and will export any matching items.
> Added: management command to dump zendesk tickets to csv

- requirements/dev.txt
- csv is a builtin and doesn't exist in pypi
- all other dependencies are pinned so doing the same with zdesk
> Fix dev dependencies

- make_a_plea/settings/base.py
- make_a_plea/settings/docker.py
- requirements/base.txt
For some reason the `production` settings isn't used for production. Instead the `docker` settings file is used. This explicitly disables secure cookies. To avoid problems on local development add the following to your `make_a_plea/settings/local.py` file.
```
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
```
This library is not used unless the `SESSION_ENGINE` is set correctly. This change also switches to the main pypi version rather than a github fork that hasn't been updated in 2 years.
Encrypted cookie compression has been enabled because we have a few text fields that can get very long.
This change will break local development unless the local settings is updated to include an `ENCRYPTED_COOKIE_KEYS` setting. This could be avoided if we pulled some of the local settings …
> Fix cookie security issues

- apps/plea/models.py
It was just printing out a message and then re-raising so it looks like
it's for debug.
We are seeing errors on dev and staging because this exception hasn't
been imported.
> Remove ProgrammingError catch

- api/api_test_v0_case.py
- api/v0/serializers.py
- apps/plea/models.py
- apps/plea/validators.py
Closes: RST-340
event_trace was not being passed to populate everywhere it was called, this was causing some audit events to be less than informative.
event_trace was not being checked when the audit event was saved, requiring it to be passed, else triggering an exception.
> Fixed: passed event_trace, checked event_trace

- apps/forms/fields.py
- apps/plea/tests/test_plea_form.py
This issue was introduced by
https://github.com/ministryofjustice/manchester_traffic_offences_pleas/pull/335
Dates are now being saved as date objects (it looks like cookie
serialisation changed from JSON based to Pickle based). Mostly this
works seamlessly, except for when returning to a page that preloads a
date field with previously entered data. This was just expecting the
date to be a string and splitting on it.
Other places that deal with this context handle both cases. For example;
https://github.com/ministryofjustice/manchester_traffic_offences_pleas/blob/master/apps/plea/models.py#L200
> Fix session loading bug

- apps/forms/templatetags/date.py
- requirements/base.txt
- requirements/dev.txt
- requirements/production.txt
- vagrant/bootstrap.sh
- vagrant/reset.sh
- vagrant/update.sh
This change adds some helper scripts to make the process and upgrades the non-django related dependencies (ie. the easy ones). There have been some difficulties with some of the Django related upgrades so I'm trying to do them in a series of smaller pull requests rather than one big one.
> RST319 upgrade dependencies step 1

- apps/plea/tasks.py
- docker/celery_defaults
- docker/run_celery.sh
After the Celery upgrade in ministryofjustice/manchester_traffic_offences_pleas#345 the Celery
worker container started failing with the following exception:
```
Traceback (most recent call last):
File "/usr/local/bin/celery", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
_main()
File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
cmd.execute_from_commandline(argv)
File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
super(CeleryCommand, self).execute_from_commandline(argv)))
File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
argv = self.setup_app_from_commandline(argv)
File …
```
> Fix Celery integration for Celery upgrade

- docker/run_celery.sh
The celery worker is exiting silently when deployed to an environment.
This change swaps the celery arguments to match the docs [1] and adds
debug logging.
[1] http://docs.celeryproject.org/en/latest/userguide/workers.html#starting-the-worker
> Add debug logging to celery worker

- apt/production.sh
- requirements/base.txt
This is apparently a silent dependency of the updated Celery SQS
transport. Running the celery worker was starting up correctly and then
just cancelling the consumer. A lot of debugging showed that the
exception causing the shutdown was being swallowed and not displayed.
> Add pycurl dependency

- api/settings/base.py
- api/v0/serializers.py
- apps/feedback/urls.py
- apps/feedback/views.py
- apps/plea/admin.py
- apps/plea/models.py
- apps/plea/urls.py
- apps/plea/views.py
- apps/receipt/urls.py
- make_a_plea/settings/base.py
- make_a_plea/urls.py
- requirements/base.txt
Depends on #348 
- Upgrade template configuration
https://docs.djangoproject.com/en/1.11/ref/templates/upgrading/
- Remove use of `urls.patterns`
- Replace `get_all_field_names()` with `get_fields()`
https://docs.djangoproject.com/en/1.11/releases/1.10/#features-removed-in-1-10
> RST 319 upgrade dependencies step 3

- apps/feedback/tests.py
- apps/forms/stages.py
- apps/forms/tests.py
- apps/plea/admin.py
- apps/plea/tests/test_nojs.py
- apps/plea/tests/test_plea_form.py
- apps/plea/tests/test_stages_data.py
The API for render_to_response was changed in 1.8 and fully deprecated
in 1.10. The fix is to use the `request` shortcut instead.
This is a quick fix for a production outage, the proper fix involving
chaning the API will come later.
https://docs.djangoproject.com/en/1.10/releases/1.8/#dictionary-and-context-instance-arguments-of-rendering-functions
https://stackoverflow.com/a/38739423
> Fix bug due to Django 1.10 upgrade

- requirements/base.txt
This change pins Kombu to an unreleased commit that fixes Celery 4 to work properly with SQS.
While testing on the dev environment it became clear that while the celery worker was able to connect to the SQS queue it wasn't actually receiving any messages off it. There is [an issue on Celery 4.0.2](https://github.com/celery/celery/issues/3672) that shows it does not work correctly with SQS. While there is [a fix](https://github.com/celery/kombu/pull/693) that that has been merged on Kombu this has not made it into a release yet which is why this change pins Kombu to a commit on master.
I have tested the Kombu commit with a minimal Django 1.11 app using SQS as the broker.
> Fix Celery 4 upgrade with SQS

- docker/run_celery.sh
- requirements/base.txt
This should have been added with #354.
Helpfully Celery doesn't throw any error it just silently exits 😡
> Add boto3 dependency for Celery 4

- apps/plea/tasks.py
- apps/plea/templates/emails/attachments/plp_email.html
- apps/plea/tests/test_email_template_output.py
- make_a_plea/templates/base_email_attachment.html
As a member of the police constabulary I need to know whether the defendant is 18 years old or under.
The last commit updates this to use a notification banner. This is using the error status colour from [govuk elements](https://govuk-elements.herokuapp.com/colour/#colour-status-colours)
and follows the style used by Digital Marketplace for [notification banners](http://alphagov.github.io/digitalmarketplace-frontend-toolkit/notification-banner.html). The colour contrast [passes WCAG AAA](http://webaim.org/resources/contrastchecker/)
Some mail clients do not load all kinds of styles. If the style fails to load it will look like this.
> RST 337 police email where defendant under 18

- apps/plea/admin.py
- apps/plea/models.py
- make_a_plea/management/commands/delete_old_data.py
Improves performance of urn search on auditevents when there are many rows in the db by removing urn substring search to hstore fields on related fields.
Adds name to the search fields
Corrects a few issues with field display and search
Remove auditevents from before the retention period
> Partially fixes: RST-442

- make_a_plea/urls.py
The ping.json view gives provides information about the version of the app that is deployed. This change adds in the docker tag of the deployed app.
This is the same as how it's [done in courtfinder](https://github.com/ministryofjustice/courtfinder-search/blob/master/courtfinder/healthcheck/urls.py#L6)
✨ This has been tested against dev ✨
> Add APP_BUILD_TAG to ping.json

- requirements/base.txt
Celery 4.1.0 has been released, this includes the newly cut Kombu 4.1.0
which includes the `boto3` changes. Upgrading to Celery 4.1.0 means that
we no longer have to pin to a specific commit of Kombu.
This supersedes #366  
http://docs.celeryproject.org/en/master/changelog.html#version-4-1-0
> Upgrade Celery to 4.1.0

- apps/plea/admin.py
- conf/locale/cy/LC_MESSAGES/django.po
- conf/locale/en/LC_MESSAGES/django.po
The admin interface does not have the same translation requirements that the frontend does.
This doesn't include any new translations just updates the line numbers due to file changes.
This was run with `$(make dev-exec) ./makemessages.sh` against a container started with `make dev`.
> Fix translations 2017 08

- api/settings/base.py
Error pages fail to render because settings inherit main site
templates with incomplete settings and dependencies
> RST-715 Disable base layout for api

- make_a_plea/urls.py
Eliminate favicon warnings from BrokenLinkEmailsMiddleware
> RST-720 Redirect /favicon.ico to static assests

- apps/plea/models.py
- apps/plea/tasks.py
- apps/plea/tests/test_email.py
- apps/plea/tests/test_models.py
- make_a_plea/settings/base.py
- make_a_plea/settings/docker.py
- make_a_plea/settings/testing.py
GSI email service is being shut down. Existing email configuration
only allows sending emails to GSI intranet.
> Allow different smtp gateways for court emails

- apps/plea/forms.py
- apps/plea/views.py
- features/court_finder.feature
- features/environment.py
- features/steps/urn.py
https://tools.hmcts.net/jira/browse/RST-1690
The whole URN entered is not validated, only the first two numbers to find the court. Behave tests added.
> RST-1690: Remove validation on URN for court finder search
